// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2832.Robot2017;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	
	
	//motor channel
		public static final int driveTrainLeftFrontChannel=1;
		public static final int driveTrainLeftRearChannel=2;
		public static final int driveTrainRightFrontChannel=3;
		public static final int driveTrainRightRearChannel=4;
		
		//Climber motor channel
		public static final int climberMotorChannel=5;
		
	    //Relay Channel
		public static final int replayChannel=0;
		
		//engine safety enable flag		
		public static final boolean engineSafetyEnabledFlag=true;
		
		//DoubleSolenoid channel
		public static final int doubleSolenoidForwardChannel=1;
		public static final int doubleSolenoidReverseChannel=0;
		
		public static final int gearScorePusherForwardChannel=3;
		public static final int gearScorePusherReverseChannel=4;
		
		public static final int gearScoreDoorForwardChannel=6;
		public static final int gearScoreDoorReverseChannel=5;
		
		//Shoter motor Channel
		public static final int shooterShooterMotorChannel=7;
		public static final int shooterFeederMotorChannel=8;
		public static final int shooterAgitatorMotorChannel=10;
		
		//ball intake motor channel
		
		public static final int ballIntakeMotorChannel=7;
		
		public static final double shooterAgitatorMotorSpeed=20d;
		public static final double shooterFeederMotorSpeed=20d;
		public static final double shooterShooterMotorSpeed=20d;
    
    
}
